### ISSUE TITLE
using protocols and store_lists is not compatible

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.db.verification.filelist#3]
When you use the new way of reading protocols, you can't leave the 'keep_read_lists_in_memory' option at its default value 'True'. Otherwise it will always return the same list for each protocol.

A solution would be to store both the group and the protocol as keys in ListReader.m_read_lists

**Comment by tiagofrepereira2012** [comment]
I think we can close this one.
The flag ```keep_read_lists_in_memory``` is working fine.

I think this was an issue 2 years ago :-P
